Generate random Password with exact length = 6, with minimum 1 
uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]

In [1]:
import string
import random


def password_creating(length):
    uppercase_1 = random.randint(0,2)  
    lowercase_1 = random.randint(3,4) 
    number_1 = random.randint(4,6)

    password = ''
      
    for i in range(length):

        if i == uppercase_1:   
            password += random.choice(string.ascii_uppercase)
                  
        elif i == lowercase_1:  
            password += random.choice(string.ascii_lowercase)
                  
        else: 
            password += random.choice(string.digits)
                        
    return password  

print(password_creating(6))

A10h77


Create 2D array and update the same 2D array provided that every 
prime number position should be replaced by cube of the positioned 
number.

In [2]:
import numpy as np
import math
def check(num):
    prime=0
    for i in  range(2,int(math.sqrt(num)+1)):
        if num%i==0:
            prime=1
            break
    if prime==0:
        return True
array=np.arange(1,26).reshape(5,5)
print(array)
print("                   ")
for i in range(len(array[0])):
    for j in range(len(array[1])):
        if check(array[i][j])==True:
            array[i][j]=array[i][j]**3
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
                   
[[    1     8    27     4   125]
 [    6   343     8     9    10]
 [ 1331    12  2197    14    15]
 [   16  4913    18  6859    20]
 [   21    22 12167    24    25]]


#Python program to get the sum of every cubed value and its previous 
integer.

In [3]:
def check(num):
    prime=0
    for i in  range(2,int(math.sqrt(num)+1)):
        if num%i==0:
            prime=1
            break
    if prime==0:
        return True
array7=np.arange(1,26).reshape(5,5)
listarr=array7.flatten()
for i in range(len(listarr)):
            if check(listarr[i])==True and listarr[i]!=1:
                  listarr[i]=listarr[i]**3+listarr[i-1]

array8=np.array(listarr).reshape(5,5)
array8

array([[    1,     9,    36,     4,   129],
       [    6,   349,     8,     9,    10],
       [ 1341,    12,  2209,    14,    15],
       [   16,  4929,    18,  6877,    20],
       [   21,    22, 12189,    24,    25]])

Checker Board Patten using Numpy:

In [5]:
array3=np.zeros((5,7))
array3
array3[0::2,0::2]=1
array3[1::2,1::2]=1
array3

array([[1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

Given two arrays, find their intersection.

In [10]:
arr_1=np.array([1, 3, 4, 5, 7])
arr_2= np.array([2, 3, 5, 6])
list(filter(lambda num:num in arr1,arr2 ))

[3, 5]

Create a 7 x 7  2D array having only multiples of 7. And return the last 
element of the same.

In [11]:
import numpy as np
n=7*7
arr=np.arange(7,n*7+1,7).reshape(7,7)
print(arr)
arr[-1][-1]

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]


343

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values

In [15]:
import random
import string
arr=np.empty((6,4),dtype="object")
for i in range(6):
   for j in range(4):
       arr[i][j] = random.choice(string.ascii_uppercase)
count=0;
for i in range(6):
   for j in range(4):
       if(arr[i][j] == 'A' or arr[i][j] == 'E' or arr[i][j] == 'I' or arr[i][j] == 'O' or arr[i][j] == 'U'):
           arr[i][j] = str(np.nan)
           count+=1
print(count)
arr

4


array([['C', 'B', 'R', 'C'],
       ['S', 'nan', 'Y', 'nan'],
       ['W', 'K', 'Q', 'N'],
       ['R', 'N', 'F', 'R'],
       ['R', 'T', 'nan', 'nan'],
       ['K', 'G', 'Y', 'J']], dtype=object)